### ISSUE TITLE
Error at game load

### ISSUE THREAD

**Issue by Oosquai** [blaxxun-boop/Resurrection#2]
I get the following red error text when I load a character into the world.  Any help please?

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Resurrection.Resurrection+AddRespawnDialog.Postfix () (at <9e14deaf26dd4ae09ca540f7f0b5bf59>:0)
(wrapper dynamic-method) Menu.DMD<Menu::Start>(Menu)

**Comment by Oosquai** [comment]
I'm not seeing this anymore, so I suspect it was a conflict with another mod on my end.  Seems to be working great!  Thank you!!

**Comment by blaxxun-boop** [comment]
Sounds like an AUGA issue.
