### ISSUE TITLE
Bug with mod

### ISSUE THREAD

**Issue by Enoticx** [blaxxun-boop/Resurrection#3]
After death, I can’t choose to stay alive and wait for help or die to the end and resurrect at the spawn point, I only have the opportunity to wait for the resurrection from an ally or exit the game when the window pops up whether I want to exit the game or not, I can’t click no it just doesn't work please add please the ability to choose to wait for resurrection or return to spawn point thank you in advance 
![image](https://user-images.githubusercontent.com/121642576/210013578-510f543d-439c-4555-afbd-bf071f146c1c.png)

**Comment by blaxxun-boop** [comment]
Remove AUGA. It is incompatible with pretty much every single mod that adds something to the UI.
You can replace it with Minimal UI, which you can make look exactly like AUGA and doesn't shit on every other mod touching the UI.
