### ISSUE TITLE
Everyone is invisible to other players after resurrecting

### ISSUE THREAD

**Issue by Xeogin** [blaxxun-boop/Resurrection#7]
Valheim: 0.218.15
BepInExPack: 5.4.2202
Resurrection: 1.0.11

This is playing with someone hosting a world started within the game client with crossplay disabled, everyone except one person has the mod installed. (all the same version as everything stated above) The person running the server also has the following mods enabled:
ConfigurationManager v1.0.5 by shudnal
JustSleep v1.0.5 by shudnal
Queue_Me_Maybe v1.1.2 by Azumatt
RemoveAttackFreezeFrame v1.0.2 by Azumatt
RequipMe v0.2.2 by Neobotics
RunningStaminaBase v1.0.4 by Azumatt
StaminaRegenerationFromFood v1.5.5 by Smoothbrain
ToolsArentTools v1.0.2 by Azumatt
UsefulTrophies v2.1.0 by probablykory
Warm_Torches v0.1.2 by VentureValheim

We haven't tried any troubleshooting yet, such as disabling all other mods, etc. as it's late and we're all going to sleep now. I can update this issue if we find anything out later this week.

**Comment by blaxxun-boop** [comment]
We are using the mod ourselves right now and it works perfectly fine. Also, make sure that EVERYONE has all mods installed that aren't simpl UI mods. Valheim is a client-authoritative game.
